---
- name: Remove unused packages.
  when: "ansible_facts['os_family'] == 'RedHat'"
  ansible.builtin.dnf:
    name:
      - nano
      - sendmail
    state: absent

- name: Include distro specific tasks.
  ansible.builtin.include_tasks: "{{ ansible_facts['os_family'] }}.yml"
