---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: libvirt
platforms:
  - name: server-security
    box: generic/debian11
    cpus: 2
    memory: 1024
provisioner:
  name: ansible
verifier:
  name: ansible
